### ISSUE TITLE
请问您出现过商品加入购物车后，规格参数出错的问题吗？

### ISSUE THREAD

**Issue by hades0525** [hftang/web_leyoushop#1]
就是item.html,获取的ownSpec属性值不对。
比如
[{skuId: 27359021784, title: "小米 MI 6.1 手机 (更新） 陶瓷黑尊享版 6GB 128GB",…},…]
0: {skuId: 27359021784, title: "小米 MI 6.1 手机 (更新） 陶瓷黑尊享版 6GB 128GB",…}
image: "http://image.leyou.com/images/10/7/1524297598540.jpg"
num: 5
**ownSpec: "{"undefined":"6GB","机身存储":"128GB"}"**
price: 329900
skuId: 27359021784
title: "小米 MI 6.1 手机 (更新） 陶瓷黑尊享版 6GB 128GB"

不知道是页面的问题还是后端取值的问题。

**Comment by hftang** [comment]
是的出现了，我再提交一下 已修复

**Comment by hftang** [comment]
> 就是item.html,获取的ownSpec属性值不对。
> 比如
> [{skuId: 27359021784, title: "小米 MI 6.1 手机 (更新） 陶瓷黑尊享版 6GB 128GB",…},…]
> 0: {skuId: 27359021784, title: "小米 MI 6.1 手机 (更新） 陶瓷黑尊享版 6GB 128GB",…}
> image: "http://image.leyou.com/images/10/7/1524297598540.jpg"
> num: 5
> **ownSpec: "{"undefined":"6GB","机身存储":"128GB"}"**
> price: 329900
> skuId: 27359021784
> title: "小米 MI 6.1 手机 (更新） 陶瓷黑尊享版 6GB 128GB"
> 
> 不知道是页面的问题还是后端取值的问题。

修复了

**Comment by hftang** [comment]
> > 就是item.html,获取的ownSpec属性值不对。
> > 比如
> > [{skuId: 27359021784, title: "小米 MI 6.1 手机 (更新） 陶瓷黑尊享版 6GB 128GB",…},…]
> > 0: {skuId: 27359021784, title: "小米 MI 6.1 手机 (更新） 陶瓷黑尊享版 6GB 128GB",…}
> > image: "http://image.leyou.com/images/10/7/1524297598540.jpg"
> > num: 5
> > **ownSpec: "{"undefined":"6GB","机身存储":"128GB"}"**
> > price: 329900
> > skuId: 27359021784
> > title: "小米 MI 6.1 手机 (更新） 陶瓷黑尊享版 6GB 128GB"
> > 不知道是页面的问题还是后端取值的问题。
> 
> 修复了

应该是前段页面的问题：
修改如下：
<div class="hr"></div>
				
				<div class="payshipInfo">
					<div class="step-tit">
						<h5>支付方式</h5>
					</div>
					<div class="step-cont">
						<ul class="payType">
							<li :class="{selected: paymentType===1}" @click="paymentType=1">微信付款<span title="点击取消选择"></span></li>
							<li :class="{selected: paymentType===2}" @click="paymentType=2">货到付款<span title="点击取消选择"></span></li>
						</ul>
					</div>
					<div class="hr"></div>
					<div class="step-tit">
						<h5>送货清单</h5>
					</div>
					<div class="step-cont">
						<ul class="send-detail">
							<li >
								<div class="sendGoods">
									<ul class="yui3-g" v-for="c in carts" :key="c.skuId">
										<li class="yui3-u-1-6">
											<span><img width="70px" height="70px" :src="c.image"/></span>
										</li>
										<li class="yui3-u-7-12">
											<div class="desc" v-text="c.title"></div>
											<div class="seven"><span v-for="(v,k) in c.ownSpec" :key="k">
                                                <span style="color: #2b2b2b" v-text="(k>0? ' | ' : '') + k + ':'"></span>{{v}}</span>
											</div>
										</li>
										<li class="yui3-u-1-12">
											<div class="price">￥{{ly.formatPrice(c.price)}}</div>
										</li>
										<li class="yui3-u-1-12">
											<div class="num">X{{c.num}}</div>
										</li>
										<li class="yui3-u-1-12">
											<div class="exit">{{c.stock > c.num ? '有货' : '缺货'}}</div>
										</li>
									</ul>
								</div>
							</li>
						</ul>
					</div>
					<div class="hr"></div>
				</div>

**Comment by hftang** [comment]
> 就是item.html,获取的ownSpec属性值不对。
> 比如
> [{skuId: 27359021784, title: "小米 MI 6.1 手机 (更新） 陶瓷黑尊享版 6GB 128GB",…},…]
> 0: {skuId: 27359021784, title: "小米 MI 6.1 手机 (更新） 陶瓷黑尊享版 6GB 128GB",…}
> image: "http://image.leyou.com/images/10/7/1524297598540.jpg"
> num: 5
> ownSpec: "{"undefined":"6GB","机身存储":"128GB"}"
> price: 329900
> skuId: 27359021784
> title: "小米 MI 6.1 手机 (更新） 陶瓷黑尊享版 6GB 128GB"
> 不知道是页面的问题还是后端取值的问题。
> 
> 修复了
> 
> 应该是前段页面的问题：
> 修改如下：
> 
> 支付方式
> 微信付款
> 货到付款
> 送货清单
> 
> {{v}}
> ￥{{ly.formatPrice(c.price)}}
> X{{c.num}}
> {{c.stock > c.num ? '有货' : '缺货'}}

![image](https://user-images.githubusercontent.com/8557368/53136537-57847b00-35ba-11e9-889c-8c5a9d1febe8.png)
